### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by RazEfron** [em0227/Trollo#1]
- [ ] Please add Bullet points for every MVP to elaborate what it'll include. Use app academy open resources - https://open.appacademy.io/learn/swe-campus-hybrid/react/mvp-list, and the lecture repo sample MVP list - https://github.com/appacademy/2021-08-09-NYC-Lecture-Notes/wiki/MVP-List

**Comment by em0227** [comment]
Hi Raz @RazEfron 
I'm done with updating the MVP list and DB Schema! Please take a look when you have time :)
